[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aicp-example-food-ordering"
version = "0.1.1"
description = "AICP Food Ordering Example"
requires-python = ">=3.10"
dependencies = ["aiohttp"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["food_ordering*"]
